### PR TITLE
add option for setting the number of digits after the decimal point

### LINKED ISSUE #5: no decimal points
hey,

i was looking to write a small lib to do exactly what yours does, except that i don't want to see the partial seconds. would you mind creating an option for that?

thanks,
coldpour

### PR DESCRIPTION
**Pull request by sindresorhus**
fixes #5

### CODE REVIEW

**Comment by sindresorhus** [comment]
@coldpour I'm not sold on the current option name, any better suggestions?

**Comment by sindresorhus** [comment]
ping @coldpour :)

**Comment by coldpour** [comment]
That's a tough one. I understand that the one you chose isn't great, but
honestly, i can't think of anything better.

**Comment by arthurvr** [comment]
Can't think of anything better eighter, but LGTM! :+1:

**Pull request merged**
